import { defineConfig } from "vite";

// GitHub Pages project site: https://qte77.github.io/paperverse/.
// `base` makes import.meta.env.BASE_URL = "/paperverse/" in the build, which
// main.ts prefixes onto the runtime fetches for data/ and the sql.js WASM.
// papers.db + positions.bin (generated by the pipeline) and sql-wasm.wasm are
// copied into public/ before build and served as-is from the site root.
export default defineConfig({
  base: "/paperverse/",
  build: {
    outDir: "dist",
  },
});
